### ISSUE TITLE
unusual symbols

### ISSUE THREAD

**Issue by lxkain** [dmort27/panphon#5]
I am working with a database that contains disordered childrens' speech. An expert phonetician transcribed the speech while also having access to a video recording of the speech production. The following symbols:

```
sˡ ɜ˞ː ə̊ ʃˡ s̬  z̥  p̪  b̪  ð̥' tʃˡ dʒˡ
```

are not in the ipa_all.csv database. Do you have opinions one way or another whether they belong? For example, I see that in `diacritic_definitions.yml` there is:

```
 - marker: ˡ
    name: "Lateral Release"
    position: post
    conditions:
      - son: "-"
        cont: "-"
        cor: "+"
        delrel: "-"
    content:
      lat: "+"
      delrel: "+"
```

and so this seems to be the reason why the laterizations above need not apply. But I'm wondering whether that only applies to typical speech...?
